### PR TITLE
feat: add a class to decompress ply files from playcanvas compression…

### PR DESCRIPTION
**Pull request by jarodabel**
I created a way to load compressed files ([from playcanvas compression](https://github.com/playcanvas/super-splat/blob/main/src/splat-convert.ts#L305)) into this viewer. Thought I would share. 

We are going implement the compression algorithm in our pipeline to help with getting big ply files to the browser. 

Full disclosure: 3D is not my main thing and definitely not parsing these files, there is probably a bunch of stuff we can improve here. I took all of this from this repo and playcanvas. 

1. Go here https://playcanvas.com/supersplat/editor
2. Upload a ply, then export it "Compressed Ply file"
image

4. Add the code snippet in this PR's readme to render
here is an example of how I did it
image

Change things a bit, generally it works, but theres some data loss. File size is not the same as before compression/decompression. 

❯ node ./util/compress.js './cacao.ply' './cacao.compressed.ply'

❯ node ./util/decompress.js ./cacao.compressed.ply ./cacao.decompressed.ply

### CODE REVIEW

**Comment by mkkellogg** [comment]
This is great! I've been meaning to add support for PlayCanvas's compressed `.ply` format for a while. I'm right in the middle of some updates that are going to refactor how the file loading code is organized (nothing too extreme), but after that I can take a look at getting this code integrated.

**Comment by jarodabel** [comment]
If you are interested I can also provide an example of how to compress into their format. Did this part for our processing pipeline.

**Comment by mkkellogg** [comment]
Hopefully I'll be able to start working on incorporating this feature soon. I'll probably rework your code, but it's a great place to start :)

**Comment by mkkellogg** [comment]
So I'm going with a stripped-down version of compressed PLY support in a new branch: https://github.com/mkkellogg/GaussianSplats3D/pull/153

For now it only supports decompression (I may add the ability to export compressed `.ply` files at some point) and automatically detects whether or not a `.ply` file is compressed.

**Comment by jarodabel** [comment]
Works for me

**Pull request closed without merging**
