### PR TITLE
Filter the path with parameters. Only the path is reserved

### PR DESCRIPTION
**Pull request by smileluck**
Hello! Thank you for the project.

## Overview
I found a problem with the incoming url. If I use a url with parameters, I don't get the type right。

## Notes
I changed the sceneFormatFromPath method, added the ability to filter parameters, and adjusted the parameter description of addSplatScene in readme

### CODE REVIEW

**Comment by mkkellogg** [comment]
There is actually a way to do this now, the `Viewer.addSplatScene()` function takes a `format` parameter of type `SceneFormat`. I'm currently working on PR with general updates so I'll make sure to add documentation to the README.

**Comment by smileluck** [comment]
Ok.  Because i am not find anything about the format of Viewer.addSplateScene() in the README, so i view the source code find this paramter. i think that if can take format from url will better, but sometimes there is a fromat like this[ [https://example.com/1.ply?sign=123132&expire=121212121].

**Comment by mkkellogg** [comment]
Yeah I forgot to add documentation to the README about the `format` parameter, sorry for the confusion!

**Comment by smileluck** [comment]
Ok. Do you know about Gaussian2D? I want to create a project about Gaussian2D，but I don't know the different between 2d and 3d gaussian render.

**Comment by mkkellogg** [comment]
2D Gaussian Splatting looks very promising as far as generating splats that are properly aligned with scene geometry and being able to generate clean, coherent, accurate meshes for a scene. I'm thinking about making this viewer compatible with that approach, but I still need to figure out the details of rendering 2D splats vs 3D.

**Pull request closed without merging**
