### PR TITLE
feat: abortable fetches

### PR DESCRIPTION
**Pull request by jarodabel**
This change is not really the most important but I added it for my use case. 

Users of my app can quickly navigate to different "captures" on a 2D map. They can click on a point marker to bring up basic information of their 3D capture. Part of this modal displays their model in a 3D viewer preview (Potree or GaussianSplats3D). 

Given how big some plys can be, I wanted to be able to abort the http request if the user closed the modal. 

image
Nov-30-2023 17-48-13

https://developer.mozilla.org/en-US/docs/Web/API/AbortController

```
plyLoader
      .loadFromURL(
        url,
        loadingProgress,
        compressionLevel,
        splatAlphaRemovalThreshold,
        controller.signal
      )
      .then((splatBuffer: any) => {
        viewer
          .loadSplatBuffer(splatBuffer, {
            splatAlphaRemovalThreshold: 5, // out of 255
            halfPrecisionCovariancesOnGPU: true,
          })
          .then(() => {
            requestAnimationFrame(update);
            setLoading(false);
          });
      })
      .catch((e: any) => {
        if (e.name === 'AbortError') {
          return;
        }
        setError(PlyErrors.UNKNOWN);
      });

    const resize = () => {
      if (!divRef.current) return;
      renderer.setSize(divRef.current.offsetWidth, divRef.current.offsetHeight);
      camera.aspect = divRef.current.offsetWidth / divRef.current.offsetHeight;
      camera.updateProjectionMatrix();
    };

    window.addEventListener('resize', resize);

    return () => {
      window.removeEventListener('resize', resize);
      controller.abort();
      while (_scene.children.length > 0) {
        _scene.remove(_scene.children[0]);
      }

      viewer.stop();
      viewer = undefined as any;
      plyLoader = undefined as any;
      renderer.dispose();
    };
```

### CODE REVIEW

**Comment by mkkellogg** [comment]
I've actually been planning on revamping the loading system to be more robust, or to possibly utilize the THREE.LoadingManager, but it will have to be after the current release I'm working on. Can you hold out until then for this capability?

**Comment by jarodabel** [comment]
Yes, definitely can.

**Comment by mkkellogg** [comment]
So I worked out a different way to abort file loads and I've got a PR for it here: [#75](https://github.com/mkkellogg/GaussianSplats3D/pull/75)

The code I've tested it with looks like:
```javascript
const abortablePromise = viewer.loadFiles([
    {
      'path': '<path to first file>',
    },
    {
      'path': '<path to second file>',
    }
]);
abortablePromise.then(() => {
    console.log("Done");
})
.catch((error) => {
    console.log("Aborted");
});

window.setTimeout(() => {
    abortablePromise.abort();
}, 2000);
```
I went this route because it avoided adding any new parameters to any of the various load functions. Let me know if that will work for you.

**Comment by jarodabel** [comment]
Sorry for late reply, LTGM. Thank you

**Pull request closed without merging**
