### PR TITLE
fix: use includes for .ply search instead of endswith

### PR DESCRIPTION
**Pull request by jarodabel**
My ply files have a token in the query parameters so I cannot search for a path that ends with .ply. I have to use includes.

### CODE REVIEW

**Comment by mkkellogg** [comment]
I'd be happy to update the file loading functions to add more control over format specification. I think maybe instead of inspecting the path or file name and guessing the format, I'll add a parameter to `Viewer.loadFile()` and `Viewer.loadFiles()` to force it to expect a certain format. If that parameter is omitted, then it can fall back on guessing based on file extension.

**Comment by jarodabel** [comment]
@mkkellogg updated based on your comments

**Comment by mkkellogg** [comment]
@jarodabel I will try to get these changes into the next release. I may tweak it a bit, but the same functionality will be there :)

**Comment by mkkellogg** [comment]
I ended up reworking the code a bit so I'll close this PR, but in the latest release ([v0.2.2](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.2.2)) you can now pass a `format` parameter as part of the `options` object to `addSplatScene()`. The value of `format` needs to be one of the values defined in the `SceneFormat` enum.

**Pull request closed without merging**
